### ISSUE TITLE
Error when embedding dinamically

### ISSUE THREAD

**Issue by flavioribeiro** [thiagopnts/clappr-zepto#1]
When trying to add `<script>` tag to import clappr dinamically, I'm getting some errors on Zepto. It doesn't occur when using `zepto-node` instead.

**Comment by flavioribeiro** [comment]
snippet to reproduce the error:

``` html
<html>
<head>
</head>
<body>
<script>
var embedScript = function(scriptUrl) { 
  var script = document.createElement("script");
  script.setAttribute("type", "text/javascript");
  script.setAttribute("async", "async");
  script.setAttribute("src", scriptUrl);
  script.onload = function() { console.log("loaded"); }
  document.body.appendChild(script);
}

embedScript("http://cdn.clappr.io/latest/clappr.js");
</script>
</body>
</html>
```

**Comment by thiagopnts** [comment]
This might be related to the way I'm making my "shimmed" version of the lib. I'll try to follow [zepto-node approach](https://github.com/fgnass/zepto-node/blob/master/index.js) to see if it works
